tests/xx7.c
this fixes testcase 7 for gcc 5.0 usage
=> an empty main() is now allowed in C, use a different function

checks/99-check-remove-rpms
This helps in cases like current Staging:B, where
* pam is newly linked against krb5 (due to the move from sun rpc over to tirpc)
* while building krb5, krb5-mini is installed into the buildroot (incl. the libraries)
* krb5 is being built, installed, removed
* for the brp checks, su is being used, but fails as pam_unix is linked to libkrb5, which has 'just been removed' again (the file was also part of krb5-mini)
Hence, avoiding that a pkg is removed if its corresponding -mini was present helps avoid this problem.
Solves the error currently seen in:
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:B/krb5/standard/x86_64
=> Do not remove packages that had a corresponding -mini installed

suse-buildsystem.sh
to allow packages like
perl-Apache-SessionX and python3-jupyter_nbconvert-doc
that output unordered hash values into the rpm
to have reproducible results (to make build-compare happy)
without finding and patching each such package individually
This change worked fine in my tests.
=> use fixed hash seed values for perl+python

suse-buildsystem.sh
because some python testsuites seemed to have failed from the 42
=> use PYTHONHASHSEED=0

checks-data/check_gcc_output
Otherwise you get:
```
I: Program causes undefined operation
(likely same variable used twiceand post/pre incremented in the same expression).
e.g. x = x++; Split it in two operations.
```
=> Fix spacing in sequence-point warning

checks-data/check_gcc_output
Newer compilers are giving great hints like
warning: implicit declaration of function 'sexlex'; did you mean 'strlen'
which matched the fortfiy check then due to strlen.
=> Fix incorrect matching due to greedy regexp (Fixes: #14)

suse-buildsystem.sh
This is required to make packages
pimcommon kpimtextedit akonadi-server kdelibs4support kdesignerplugin
build reproducibly, because qt5's moc tool uses a [QHash](http://doc.qt.io/qt-5/qhash.html#qSetGlobalQHashSeed)
to produce .cpp files that get linked into
/usr/lib64/qt5/plugins/designer/FOO.so files
=> export QT_HASH_SEED

suse-buildsystem.sh
Otherwise this happens:
QT_HASH_SEED: forced seed value is not 0, cannot guarantee that the hashing functions will produce a stable value.
=> QT_HASH_SEED has to be 0

checks/50-check-kernel-build-id
Add a check to verify the consistency of kernel build ids.
Prevent further regressions (bsc#964063, hsc#768504)
=>  Add kernel-build-id consistency check

suse-buildsystem.sh
without the FORCE_SOURCE_DATE variable, packages like libvmime varied
because pdflatex ignored the SOURCE_DATE_EPOCH value
=> make all OBS pdflatex builds reproducible

suse-ignored-rpaths.conf
To solve https://bugzilla.opensuse.org/show_bug.cgi?id=1109470
it is nicer to track this file in git
instead of the .spec file
content is the previous content with `%_lib` expanded to both `lib` and `lib64`
=> Add suse-ignored-rpaths.conf

checks-data/findfileconflicts
Fixing #24 (https://github.com/openSUSE/post-build-checks/issues/24). Ghosts are not really files and don't take part in conflicts so there is no need to push them to check.
=> Ignore ghosts

checks/99-check-remove-rpms
The package libgomp1 is being pulled in by RPM (since 4.15, for parallel processing).
While building alternative versions of gcc, the post-build-checks install (forcibly)
libgomp1-gccX, overwriting /usr/lib64/libgomp.so.1. Later on, the RPMs are being uninstalled again,
resulting in libgomp.so.1 being deleted (libgomp1 being broken)
Any future call to RPM will fail, as depending libraries are now missing. Since this is the same
special case as with libgcc and libstdc++, we handle libgomp the same way by keeping the freshly
built RPM installed
=> 99-check-remove-rpms: preserve libgomp variants

checks-data/findfileconflicts
Ghost files are flagged with a bit. So we need to check for absence
of the bit if we want to put non-ghost files into the hash. The
previous logic would only put ghost files into the hash.
=> Fix ghost logic

checks/99-check-remove-rpms
Like with coreutils, the packages containing su and sh should not
be de-installed as we need them to finish the build.
=> Don't de-install the packages containing su and sh

checks/99-check-remove-rpms
find, gzip and cpio are required to finish build, so don't remove them.
=> Don't remove find, gzip and cpio

checks/99-check-remove-rpms
That's needed to have two pam_unix variants: one with and one without NIS support. If any of the pam_unix variants get removed, the build system will break.
=> Don't deinstall any pam_unix variant

checks/00-check-install-rpms, checks/50-check-installtest, checks/99-check-remove-rpms
skip installing the built rpms if the architecture is neither
the target arch nor noarch and also subsequently skip the
pre/post install checks and the removal of the installed rpms
=> support cross builds

checks/99-check-remove-rpms
Previously only the bash-sh was preserved, now also the target
of the symlink is marked as to be kept. this allows other dropins
like dash to be providing a /usr/bin/sh symlink.
Also cleanup the code to avoid repeated calls to rpm in the chroot.
=> keep package that provides /usr/bin/sh

checks/50-check-lanana
There were a lot of string processing in bash and rpm(1) invocations.
Reduces overhead by ~ 10%
=> Speedup check-lanana

checks/50-check-invalid-provides, checks/50-check-permissions
this also saves a bit of time on builds with large number of subpackages.
=> use predictable C locale for rpm listing

checks/50-check-kernel-build-id
check for kernels with extensions gz xz zst and in /boot and in /usr/lib/modules/$version ... to allow for usermerged and non-usermerged setups
=> update 50-check-kernel-build-id for compression and location of kernels

checks/50-check-invalid-requires, checks/50-check-libtool-deps
grep 3.8 starts throwing warnings, and `egrep`/`fgrep` will be dropped long term
https://bugzilla.opensuse.org/show_bug.cgi?id=1203092
=> Convert egrep/fgrep calls to grep -E/-F, respectively

checks/99-check-remove-rpms
`99-check-remove-rpms` tries to **not** remove packages that provide essential utilities like `cat`, `date`, `rm`, etc. Before this commit, it would only check for the actual file, but tiny coreutils replacements like `toybox` or `busybox` often provide `-symlink` packages, which provide a bunch of symlinks from `/usr/bin/rm -> /bin/{busybox,toybox}`.
`99-check-remove-rpms` would then keep the symlink package, but remove `toybox`/`busybox` effectively breaking the buildroot. By adding a `readlink` check, we will no longer remove `busybox` & `toybox` in such a case.
=> Follow symlinks to infer which packages to keep

checks/99-check-remove-rpms
Some util-linux binaries are needed to run and shutdown the VM.
This change is needed to build util-linux-mini conflicting with util-linux. Otherwise the build uninstalls umount and swapoff and the VM will fail to land.
=> Add mount, umount, swapon and swapoff to ESSENTIAL_PKG_TO_KEEP

post-mkbaselibs-checks/01-delete-x86_64-subarches
Flatpak builds don't create the `RPMS` directory which causes the subsequent `find $BUILD_ROOT$TOPDIR/RPMS` to fail
=> delete-x86_64-subarches: don't search in RPMS dir if not present

suse-buildsystem.sh
replacing rpm its %source_date_epoch_from_changelog . This instead also increments the date by the build counter, which OBS puts into the release field of rpm. When available it uses the mtime that OBS its scmsync obtains from the git HEAD commit date instead of from the changelog.
All this can be disabled by setting the rpm macro
%disable_obs_set_source_date_epoch to Y .
This uses new variables in /.buildenv that were implemented in https://github.com/openSUSE/obs-build/commit/5d1da8553791ecdf35ab538bddd6afa4494d66d0 .
See https://reproducible-builds.org/docs/source-date-epoch/ for general introduction.
Increasing the date by the build counter is necessary, so that that even for rebuilds with unchanged source but updated build depends the date is always increased, such that no build with …
=> Set SOURCE_DATE_EPOCH

finalize-system/01-add_abuild_user_to_trusted_group
That is no longer installed in Tumbleweed buildenvs, we can do without
=> Add abuild to trusted group without using usermod

suse-buildsystem.sh
replacing rpm its %source_date_epoch_from_changelog . This instead also
increments the date by the build counter obtained from OBS. When
available it uses the mtime that OBS its scmsync obtains from the git
HEAD commit date instead of from the changelog.
It exports the old date in SOURCE_DATE_EPOCH and the new incremented
date in SOURCE_DATE_EPOCH_MTIME. rpm will use
SOURCE_DATE_EPOCH_MTIME for for file mtimes and the old date for
everything else.
All this can be disabled by setting the rpm macro
%disable_obs_set_source_date_epoch to Y .
This uses new variables in /.buildenv that were implemented in
https://github.com/openSUSE/obs-build/commit/5d1da8553791ecdf35ab538bddd6afa4494d66d0
.
See
https://reproducible-builds.org/docs/source-date-epoch/#interaction-of-source_date_epoch-with-automat …
=> Set SOURCE_DATE_EPOCH (2nd try)

suse-buildsystem.sh
```
[    2s] WARNING could not set SOURCE_DATE_EPOCH, ensure BUILD_RELEASE is set in /.buildenv
[    2s] /etc/profile.d/suse-buildsystem.sh: line 53: test: : integer expression expected
```
There are `unset` statements right above the `-ge` test, but `-ge` must only ever be called with number input (which an unset variable is not).
=> Guard against "integer expression expected" error
